name: 上传到CC-Aria2网页进行下载
on:
  gollum

jobs:
  airacc:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.1.0
    - name: 安装python
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7
